# Generated by Django 3.2.19 on 2025-05-26 11:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('structure', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserStructure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('role', models.CharField(default='member', max_length=50)),
                ('structure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_assignments', to='structure.structure')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='structure_assignments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-assigned_at'],
                'unique_together': {('user', 'structure')},
            },
        ),
    ]
