# Generated by Django 3.2.19 on 2025-05-26 11:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('game_type', '0001_initial'),
        ('structure', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PayoutRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payout_rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('condition', models.JSONField(help_text='JSON defining the winning condition')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('game_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payout_rules', to='game_type.gametype')),
                ('owner_structure', models.ForeignKey(limit_choices_to={'node_type': 'bank'}, on_delete=django.db.models.deletion.CASCADE, related_name='payout_rules', to='structure.structure')),
            ],
            options={
                'ordering': ['game_type', '-created_at'],
                'unique_together': {('game_type', 'condition', 'owner_structure')},
            },
        ),
    ]
