# Generated by Django 3.2.19 on 2025-05-26 11:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('structure', '0001_initial'),
        ('winning_record', '0001_initial'),
        ('origin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Draw',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('draw_datetime', models.DateTimeField()),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='scheduled', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('origin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='draws', to='origin.origin')),
                ('owner_structure', models.ForeignKey(limit_choices_to={'node_type': 'bank'}, on_delete=django.db.models.deletion.CASCADE, related_name='draws', to='structure.structure')),
                ('winning_numbers', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='draw', to='winning_record.winningrecord')),
            ],
            options={
                'ordering': ['-draw_datetime'],
            },
        ),
    ]
