# Generated by Django 3.2.19 on 2025-05-26 11:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('draw', '0001_initial'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinancialStatement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('total_collected', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('total_paid', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('net_result', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('content_type', models.ForeignKey(limit_choices_to={'model': 'structure'}, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('draw', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='financial_statements', to='draw.draw')),
            ],
            options={
                'verbose_name': 'Financial Statement',
                'verbose_name_plural': 'Financial Statements',
                'ordering': ['-draw__draw_datetime', 'content_type', 'object_id'],
            },
        ),
        migrations.AddIndex(
            model_name='financialstatement',
            index=models.Index(fields=['content_type', 'object_id'], name='financial_s_content_428d96_idx'),
        ),
        migrations.AddIndex(
            model_name='financialstatement',
            index=models.Index(fields=['draw'], name='financial_s_draw_id_5bb007_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='financialstatement',
            unique_together={('draw', 'content_type', 'object_id')},
        ),
    ]
